services:
  vowerp-frontend:
    image: ghcr.io/tarunsadhukhan/sjm3ui:latest
    build:
      context: .
      args:
        NEXT_PUBLIC_BACKENDHOST: http://vowerp-backend:8000
        NEXT_PUBLIC_API_BASE_URL: /api
        USE_NEXT_PROXY: "true"
        NEXT_PUBLIC_STATIC_SUBDOMAIN: sjm
    container_name: vowerp-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Kolkata
    networks:
      - vowerp

networks:
  vowerp:
    external: true
